### ISSUE TITLE
Create a footer 

### ISSUE THREAD

**Issue by kwiens** [iFixit/footer#1]
Following our [engineering guidelines](https://docs.google.com/document/d/1RJ4xsCN3FhpM9atkC_yiUCjhilgWOsad4uA4TY83cJk/edit), build a React component for the iFixit footer. This will be used on Shopify and eventually iFixit.com.

Guidelines
- Use [Core primitives](https://github.com/iFixit/core-primitives) wherever you can.
- Everything should be a functional component.
- Use styled components.
- Use prettier. 
- Publish to NPM.
- Localize strings with _js(‘...’). Example.
- Try using preact instead of React.
- Use our CDN (we’ll give you access to Charge to upload files) for assets.

Implement this UI as a functional component: https://ifixit-design.webflow.io/footer

The links and images will change based on the region. Spec will be forthcoming from @jeffsnyder.

The only dynamic elements are the region selector and the language selector. We've already implemented these selectors and need to export it to NPM for you. @zdmitchell can get this code for you. You may need to make some modifications to those interactions.

Open questions:
* When should this component render? 
* How do we make it accessible to Google? (Or, is this necessary? We could render this server side on iFixit and client side on Shopify.)

**Comment by jeffsnyder** [comment]
Here are [text and links for the footer content](https://docs.google.com/spreadsheets/d/1yoTQqIFI2Fy4W9CfMnM5F0CjZ9YLAeK56yLyajE2Sj8/edit#gid=0).

This has all of the links for the US and US Shopify store. Other regions are so far incomplete, but I think you can use what we have here to get started. I _think_ my labels are intuitive—if not, just compare the values of `ifixit.com Text` to the mockup and it'll all make sense. 

The only thing to add is that the "Pay/Logistics Badges" should be monochrome as in the mockup.

**Comment by dhmacs** [comment]
@kwiens we are reading through the Engineering Partner Guidelines, and the link to the localize example is broken (https://github.com/iFixit/device-picker/blob/master/src/NoResults.tsx#L31)

Maybe it's because we don't have access to the repo?

**Comment by zdmitchell** [comment]
> Maybe it's because we don't have access to the repo?

You're probably right @dhmacs. It was pointing to this line:
```<p>{_js('No matches found. Did you spell it correctly?')}</p>```
Basically, you just need to pass you text to the function `__js()` to localize it.

**Comment by dhmacs** [comment]
## Status update

We've come up with a few ideas on how to implement the footer package, and we present them here to get feedback and see if this is the right direction before implementing anything.

1. We investigated on how to build Preact components packages and we think [Microbundle](https://github.com/developit/microbundle) is the way to go (it's built by the same author of Preact)
2. We propose to use [Storybook](https://storybook.js.org/) to develop components in isolation. This would also serve as [documentation](https://storybook.js.org/docs/preact/writing-docs/introduction) on how to use the components and a [testing solution](https://storybook.js.org/docs/preact/workflows/testing-with-storybook).
3. We thought of implementing the footer as a set of composable components so that the consumer of the library will be able to customize it without having to change the library code. Here's a first draft of the components we have identified:

    ![footer](https://user-images.githubusercontent.com/4640135/105387227-9cd1dd00-5c15-11eb-9c9b-9736634f3026.png)

    Some of these components (e.g. Stack) may very well be generic components reusable across the whole site. The usage would be something like this:
    ```jsx
    <Footer>
      <FooterSection backgroundColor={color.gray1}>
        <Stack justify="center">
          <StatLabel>View Statistics:</StatLabel>
          <Stack divider={<Divider />}>
            <Stat label="Past 24 hours" value="123" />
            <Stat label="7 days" value="123" />
          </Stack>
        </Stack>
      </FooterSection>
      <FooterSection backgroundColor={color.blueDark1}>
        <Stack>
          <Stack direction="column">
            <FooterLink href="#">About us</FooterLink>
            <FooterLink href="#">Customer Support</FooterLink>
            <FooterLink href="#">Careers</FooterLink>
          </Stack>
          <Stack direction="column">
            <FooterLink href="#">Press</FooterLink>
            <FooterLink href="#">News</FooterLink>
            <FooterLink href="#">Contribute</FooterLink>
          </Stack>
          <Stack direction="column">
            <FooterLink href="#" prefix={<FacebookLogo />}>
              Facebook
            </FooterLink>
            <FooterLink href="#" prefix={<FacebookLogo />}>
              Twitter
            </FooterLink>
          </Stack>
        </Stack>
        <Grid templateColumns="repeat(3, 1fr)" gap={space[1]}>
          <FooterLogo src=".."></FooterLogo>
          <FooterLogo src=".."></FooterLogo>
          <FooterLogo src=".."></FooterLogo>
        </Grid>
      </FooterSection>
      <FooterSection backgroundColor={color.blueDark1}>
        <Stack justify="space-between">
          <Stack>...</Stack>
          <Stack>...</Stack>
        </Stack>
      </FooterSection>
    </Footer>
    ```
Let us know if this is what you have in mind.

P.S.: Currently we don't have write access to this repo, do you want us to fork it and submit PRs ?

**Comment by dhmacs** [comment]
@zdmitchell @sterlinghirsh 
Following up on your decision to use React for this project, we may switch Microbundle for [tsdx](https://tsdx.io/) which is more React specific. On the other hand, if we want to make the refactor easier should you decide to switch to Preact, we could still stick to Microbundle.

Beside that, if you can give us your feedback on the above comment we can move forward to implement the package 👍

**Comment by zdmitchell** [comment]
> Following up on your decision to use React for this project, we may switch Microbundle for [tsdx](https://tsdx.io/) which is more React specific. On the other hand, if we want to make the refactor easier should you decide to switch to Preact, we could still stick to Microbundle.

@dhmacs tsdx is fine with us. Use whatever you think is best. I wouldn't let the possibility of switching to Preact influence your decision.

**Comment by kwiens** [comment]
That all sounds good to me! I gave you write access to this repo.

We have used Storybook ourselves off and on—makes sense.

@zdmitchell Do we want view count stats as part of this? We probably do want do add our pixel ping to Shopify.

**Comment by zdmitchell** [comment]
> Do we want view count stats as part of this?

Hmm not sure exactly. Probably eventually, but I'm not sure if we need it right away.

**Comment by Annika29** [comment]
Footer assets are here: https://github.com/iFixit/footer/issues/8
