### ISSUE TITLE
footer assets

### ISSUE THREAD

**Issue by Annika29** [iFixit/footer#8]
## footer assets

- social icons + repair.org icon
[footer-icon.zip](https://github.com/iFixit/footer/files/6051396/footer-icon.zip)

- shipping/payment service icons
[logos.zip](https://github.com/iFixit/footer/files/6051397/logos.zip)

Preview of shipping/payment service icons:
<img width="941" alt="109063674-72ad8800-76b7-11eb-92df-a9435885fe59" src="https://user-images.githubusercontent.com/35045100/109334710-ef567880-7815-11eb-8c67-c58b131bd1bd.png">

**Comment by dhmacs** [comment]
@Annika29 The "Dark mono" version of the shipping/payments icons have some issues.. Some of them are actually colored.

<img width="873" alt="Screen Shot 2021-09-03 at 12 03 44" src="https://user-images.githubusercontent.com/4640135/131988233-189c147d-958b-44d3-b5d0-db0aa4020ffa.png">

**Comment by Annika29** [comment]
That's interesting...I'll check with Ben and double back if we need to look into fixing this.

**Comment by dhmacs** [comment]
@Annika29 One more thing, can I have the logos without padding around them?

**Comment by Annika29** [comment]
Hey @dhmacs! I can look at doing that, but that will require me to go in and fiddle with the figma files a bit.

Also, @bhuminson is working on integrating the footer on our side, is that what you're doing here https://github.com/iFixit/react-commerce/pull/78?

**Comment by dhmacs** [comment]
> Hey @dhmacs! I can look at doing that, but that will require me to go in and fiddle with the figma files a bit.

Ok, let me know when you are done. 👍  Those images have to be uploaded to Strapi.

> Also, @bhuminson is working on integrating the footer on our side, is that what you're doing here [iFixit/react-commerce#78](https://github.com/iFixit/react-commerce/pull/78)?

@Annika29 Yes! That's already done. Since that PR depends on https://github.com/iFixit/react-commerce/pull/77, I'm waiting for that one to be merged first.

**Comment by Annika29** [comment]
[iFixit Footer.zip](https://github.com/iFixit/footer/files/7131806/iFixit.Footer.zip)

**Comment by Annika29** [comment]
@dhmacs here is the shipping/payment service icons without padding, is that what you needed?

Let me know if you need anything else, or need those in a different format (svg perhaps).

**Comment by dhmacs** [comment]
Hey @Annika29, the size should be ok now, but they are not monochrome.

They should look like this: 

<img width="753" alt="Screen Shot 2021-09-13 at 08 12 14" src="https://user-images.githubusercontent.com/4640135/133032514-04c68ca5-cc44-4a7b-be4f-37ba595d3fc7.png">

Instead they look like this:

<img width="231" alt="Screen Shot 2021-09-13 at 08 12 59" src="https://user-images.githubusercontent.com/4640135/133032591-70b69d9b-f6ab-44cc-93a3-947e1fdeb9fc.png">

**Comment by Annika29** [comment]
hmm interesting, I will take a look today and see why that's happening, they should be the monochrome ones

**Comment by Annika29** [comment]
figured it out, weird setting in figma was overriding the overlays, these should be good now :)

[iFixit Footer (1).zip](https://github.com/iFixit/footer/files/7157905/iFixit.Footer.1.zip)

**Comment by dhmacs** [comment]
@Annika29 Thanks, now the assets colors seems right, but this last export has a couple of new issues:

- Images have background colors, but they should be transparent
- Images are too small

![image](https://user-images.githubusercontent.com/4640135/133255759-5c3f7c12-f1ee-4e43-acee-95ecd2e84071.png)

**Comment by Annika29** [comment]
hmm okay try these

<img width="80" alt="visa" src="https://user-images.githubusercontent.com/35045100/133345716-10551360-241e-45ff-bf46-65a1bf839172.png">
<img width="50" alt="ups" src="https://user-images.githubusercontent.com/35045100/133345717-f6d6f0c9-fe2c-474f-950d-dcffa2de8c79.png">
<img width="157" alt="hermes" src="https://user-images.githubusercontent.com/35045100/133345718-c9c873e0-5d75-4c78-800d-ff0868d5ba7e.png">
<img width="57" alt="mc" src="https://user-images.githubusercontent.com/35045100/133345719-ca126626-f93c-4b15-91f5-5fc2efd86a3e.png">
<img width="91" alt="paypal" src="https://user-images.githubusercontent.com/35045100/133345720-78e57837-d4b4-4ba5-9c6d-73c8467afd76.png">
<img width="152" alt="sofort" src="https://user-images.githubusercontent.com/35045100/133345721-750650e5-297f-486f-a22b-0ce40755f496.png">
<img width="97" alt="fedex" src="https://user-images.githubusercontent.com/35045100/133345722-5069729c-3d34-4c52-afeb-1683faf98dbf.png">
<img width="149" alt="dhl" src="https://user-images.githubusercontent.com/35045100/133345723-05420800-2105-42c2-9eef-1ed94d8270a1.png">
<img width="94" alt="amex" src="https://user-images.githubusercontent.com/35045100/133345724-79855a2f-74e8-4bb8-b84c-0f477b7dc017.png">

**Comment by dhmacs** [comment]
@Annika29 these seems to work 👍 Please send me the zip file containing them all

**Comment by Annika29** [comment]
here you go: [footer_icons.zip](https://github.com/iFixit/footer/files/7171267/footer_icons.zip)

**Comment by dhmacs** [comment]
@Annika29 Sorry to bother you again, but we still have some issues 😅  :

1. "Discover" logo does not seem correctly exported
  ![Screen Shot 2021-09-17 at 15 06 22](https://user-images.githubusercontent.com/4640135/133787299-b9d3c95f-6441-479c-9af4-6d21dcfec9a7.png)
2. Many logos are missing, such as Google Pay and Apple Pay. Can you please make sure to export all the logos reported [here](https://docs.google.com/spreadsheets/d/1yoTQqIFI2Fy4W9CfMnM5F0CjZ9YLAeK56yLyajE2Sj8/edit#gid=0) ?

**Comment by Annika29** [comment]
Just when I thought this was good 😆  I'll try to take a look at this today or tomorrow for you when I have time to dive back into figma
